### ISSUE TITLE
Misused weak pointer

### ISSUE THREAD

**Issue by kkauder** [jhputschke/J2XSCAPE-DEV#2]
https://github.com/jhputschke/J2XSCAPE-DEV/blob/7670b756b56371fc25e75d83a71ea199e6cdfba8/src/framework/ModuleClock.cc#L33

This will crash if the weak pointer is 0. Always use  auto p = wp.lock(); if (p) ...

**Comment by jhputschke** [comment]
Thanks. Good point. In that case, I think we have to through a warning and potentially exit since it won't work anyways as expected ...

**Comment by jhputschke** [comment]
Fixed.
